backend:
  name: git-gateway
  repo: franknoirot/megan-rodgers

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://meganrodgers.me
display_url: https://meganrodgers.me
logo_url: https://meganrodgers.me/uploads/final-logo.jpg

collections:
  - name: "collections"
    label: "Collections"
    label_singular: "Collection"
    folder: "collections"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order of Appearance", name: "order", widget: "number"}
      - {label: Season, name: season, widget: string}
      - label: Featured Image
        name: featuredImage
        widget: object
        fields:
          - {label: Image, name: src, widget: image}
          - {label: Title, name: title, widget: string}
          - {label: Alt Text, name: alt, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Main Color
        name: color
        widget: object
        fields:
          - label: "R"
            name: "r"
            widget: "number"
            default: 125
            valueType: "int"
            min: 1
            max: 255
          - label: "G"
            name: "g"
            widget: "number"
            default: 125
            valueType: "int"
            min: 1
            max: 255
          - label: "B"
            name: "b"
            widget: "number"
            default: 125
            valueType: "int"
            min: 1
            max: 255
      - label: "Process Steps"
        name: "processSteps"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - label: "Process Images"
            name: "images"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: "object"
                fields:
                  - {label: "Image File", name: "src", widget: "image"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Alt Text", name: "alt", widget: "string"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "pages/index.md"
        fields:
          - {label: Title, name: title, widget: hidden, default: Home}
          - {label: Main Logo, name: logo, widget: image}
          - label: "Featured Collection"
            name: featuredCollection
            widget: "relation"
            collection: "collections"
            searchFields: [title"]
            valueField: "title"
            displayFields: ["title"]
            multiple: false
      - label: "About"
        name: "about"
        file: "pages/about.md"
        fields:
          - {label: Title, name: title, widget: hidden, default: About}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: Images
            name: imgList
            widget: list
            allow_add: false
            field: {label: "Image File", name: img, widget: image}
          - {label: Resume, name: resume, widget: file}
      - label: "Lookbook"
        name: "lookbook"
        file: "pages/lookbook.md"
        fields:
          - {label: Title, name: title, widget: hidden, default: Lookbook}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Images"
            name: "imageGallery"
            widget: "list"
            identifier_field: src
            fields: 
              - label: "Image File"
                name: "src"
                widget: "image"
              - label: "Is the image vertical?"
                name: isVert
                widget: boolean
                default: false
              - label: "Collection"
                name: "collection"
                widget: "string"
              - label: "Caption"
                name: "caption"
                widget: "string"
      - label: "Textiles"
        name: "textiles"
        file: "pages/textiles.md"
        fields:
          - {label: Title, name: title, widget: hidden, default: Textiles}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Images"
            name: "imageGallery"
            widget: "list"
            identifier_field: src
            fields: 
              - label: "Image File"
                name: "src"
                widget: "image"
              - label: "Is the image vertical?"
                name: isVert
                widget: boolean
                default: false
              - label: "Collection"
                name: "collection"
                widget: "string"
              - label: "Caption"
                name: "caption"
                widget: "string"
