backend:
  name: git-gateway
  repo: franknoirot/megan-rodgers

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "collections"
    label: "Collections"
    label_singular: "Collection"
    folder: "collections"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: Season, name: season, widget: string}
      - label: Featured Image
        name: featuredImage
        widget: object
        fields:
          - {label: Image, name: src, widget: image}
          - {label: Title, name: title, widget: string}
          - {label: Alt Text, name: alt, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Main Color
        name: color
        widget: object
        fields:
          - label: "R"
            name: "r"
            widget: "number"
            default: 125
            valueType: "int"
            min: 1
            max: 255
          - label: "G"
            name: "g"
            widget: "number"
            default: 125
            valueType: "int"
            min: 1
            max: 255
          - label: "B"
            name: "b"
            widget: "number"
            default: 125
            valueType: "int"
            min: 1
            max: 255
      - label: "Process Steps"
        name: "processSteps"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - label: "Images"
            name: "images"
            widget: "list"
            field:
              {
                label: "Image"
                name: "image"
                widget: "object"
                fields:
                  - {label: "Image File", name: "src", widget: "image"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Alt Text", name: "alt", widget: "string"}
              }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "pages/index.md"
        fields:
          - {label: Title, name: title, widget: hidden, default: Home}
          - {label: Main Logo, name: logo, widget: image}
          - label: "Featured Project"
            name: featuredProject
            widget: "relation"
            collection: "projects"
            searchFields: ["title"]
            valueField: "slug"
            displayFields: ["title"]
            multiple: false
      - label: "About Page"
        name: "about"
        file: "pages/about.md"
        fields:
          - {label: Title, name: title, widget: hidden, default: About}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: Images
            name: images
            widget: list
            field: {label: Image, name: image, widget: image}
          - {label: Resume, name: resume, widget: file}
