backend:
  name: git-gateway
  repo: franknoirot/megan-rodgers

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: Season, name: season, widget: string}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Process Steps"
        name: "processSteps"
        widget: "list"
        fields:
          - {label: Name, name: name, widget: string}
          - label: Images
            name: images
            widget: list
            field: {label: Image, name: image, widget: image}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "pages/index.md"
        fields:
          - {label: Title, name: title, widget: hidden, default: Home}
          - {label: Main Logo, name: logo, widget: image}
          - label: "Featured Project"
            name: featuredProject
            widget: "relation"
            collection: "projects"
            searchFields: ["title"]
            valueField: "slug"
            multiple: false
      - label: "About Page"
        name: "about"
        file: "pages/about.md"
        fields:
          - {label: Title, name: title, widget: hidden, default: About}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: Images
            name: images
            widget: list
            field: {label: Image, name: image, widget: image}
          - {label: Resume, name: resume, widget: file}
