backend:
  name: git-gateway
  repo: franknoirot/megan-rodgers

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "id", name: "ID", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Process Steps"
        name: "processSteps"
        widget: "list"
        fields:
          - {label: Name, name: name, widget: string}
          - label: Images
            name: images
            widget: list
            field: {label: Image, name: image, widget: image}