backend:
  name: git-gateway
  repo: franknoirot/megan-rodgers

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "id", name: "ID", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Process Steps"
        name: "processSteps"
        widget: "list"
        fields:
          - {label: Name, name: name, widget: string}
          - label: Images
            name: images
            widget: list
            field: {label: Image, name: image, widget: image}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "src/content/index.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Tagline, name: tagline, widget: string}
          - label: Featured Projects
            name: featuredProjects
            widget: list
            fields:
              - label: "Projects"
                name: "projects"
                widget: "relation"
                collection: "projects"
                searchFields: ["title"]
                valueField: "title"
                displayFields: ["title"]